#!/bin/zsh

FOAM_VERSION={{FOAM_VERSION}}

echo "---------------------------------------------------------------------------"
echo "             |                 °°° OpenFOAM-v$FOAM_VERSION.app °°°                  "
echo "   ( )       |         https://github.com/gerlero/openfoam$FOAM_VERSION-app         "
echo "  ( )    ( ) |                                                             "
echo "      ( )    | Precompiled OpenFOAM v$FOAM_VERSION for macOS                        "
echo "             | Built from the OpenFOAM source code (www.openfoam.com)      "
echo "---------------------------------------------------------------------------"

echo "Mounting the OpenFOAM-v$FOAM_VERSION volume..."
DMG_FILE="${0:A:h}/../Resources/OpenFOAM-v$FOAM_VERSION.dmg"
hdiutil attach "$DMG_FILE" -quiet
echo "You can safely unmount the volume from the Finder after use."

echo "Activating the OpenFOAM environment..."
"/Volumes/OpenFOAM-v$FOAM_VERSION/etc/openfoam" "$@"
