SCRIPT_DIR="$(\cd $(dirname ${BASH_SOURCE:-${ZSH_NAME:+$0}}) && \pwd -L)"
APP_BUNDLE="${SCRIPT_DIR}/../.."

"${APP_BUNDLE}/Contents/MacOS/volume" -quiet mount

VOLUME=`"${APP_BUNDLE}/Contents/MacOS/volume" -show-prefix`

if [ ${BASH_VERSINFO:-4} -ge 4 ]; then
    # Keep the volume directory open in this process (prevents accidental ejection)
    exec {fd}<"$VOLUME"
fi

. "$VOLUME/etc/bashrc"
