SCRIPT_DIR="$(\cd $(dirname ${BASH_SOURCE:-${ZSH_NAME:+$0}}) && \pwd -L)"

"$SCRIPT_DIR/../volume" -quiet mount

VOLUME=`"$SCRIPT_DIR/../volume" -show-prefix`

if [ ${BASH_VERSINFO:-4} -ge 4 ]; then
    # Keep the volume directory open in this process (prevents accidental ejection)
    exec {fd}<"$VOLUME"
fi

. "$VOLUME/etc/bashrc"
