script_dir="$(\cd $(dirname ${BASH_SOURCE:-${ZSH_NAME:+$0}}) && \pwd -L)"

"$script_dir/../volume" -quiet mount

volume=`"$script_dir/../volume" -show-prefix`

if [ ${BASH_VERSINFO:-4} -ge 4 ]; then
    # Keep the volume directory open in this process (prevents accidental ejection)
    exec {fd}<"$volume"
fi

. "$volume/etc/bashrc"
