#!/bin/zsh -e

app_name="{{app_name}}"

app_bundle="${0:A:h:h:h:h}"

if [ $# -eq 0 ]; then
    echo "---------------------------------------------------------------------------" 1>&2
    echo "             |                                                             " 1>&2
    echo "   ( )       |                 °°° $app_name.app °°°                  " 1>&2
    echo "  ( )    ( ) |                                                             " 1>&2
    echo "      ( )    | Native OpenFOAM for macOS                             " 1>&2
    echo "             | {{APP_HOMEPAGE}}                 " 1>&2
    echo "---------------------------------------------------------------------------" 1>&2

    "$app_bundle/Contents/Resources/volume" mount 1>&2

    echo "Activating the OpenFOAM environment..." 1>&2
else
    "$app_bundle/Contents/Resources/volume" -quiet mount 1>&2
fi

volume=$("$app_bundle/Contents/Resources/volume" -show-prefix)

# Keep the volume directory open in this process (prevents accidental ejection)
exec {fd}<"$volume"

PATH="$volume/usr/opt/bash/bin${PATH+:$PATH}" exec bash "$volume/etc/openfoam" "$@"
