SCRIPT_DIR="$(\cd $(dirname ${BASH_SOURCE:-${ZSH_NAME:+$0}}) && \pwd -L)"

"$SCRIPT_DIR/volume" -quiet mount

VOLUME=`"$SCRIPT_DIR/volume" -show-prefix`

# Keep the volume directory open in this process (prevents accidental ejection)
exec {fd}<"$VOLUME"

. "$VOLUME/etc/bashrc"
