#!/usr/bin/osascript

set MacOSDir to (path to me as text) & "::"

tell application "Terminal"
    do script (quoted form of POSIX path of MacOSDir) & "../Resources/etc/openfoam"
    activate
end tell
