#!/bin/zsh -e

APP_BUNDLE="${0:A:h:h:h}"
APP_NAME="${APP_BUNDLE:t:r}"

echo "---------------------------------------------------------------------------"
echo "             |                                                             "
echo "   ( )       |                 °°° $APP_NAME.app °°°                  "
echo "  ( )    ( ) |                                                             "
echo "      ( )    | Precompiled OpenFOAM for macOS                        "
echo "             | {{APP_HOMEPAGE}}                 "
echo "---------------------------------------------------------------------------"

"$APP_BUNDLE/Contents/MacOS/volume" mount

VOLUME=$("$APP_BUNDLE/Contents/MacOS/volume" -show-prefix)

# Keep the volume directory open in this process (prevents accidental ejection)
exec {fd}<"$VOLUME"

echo "Activating the OpenFOAM environment..."
exec bash "$VOLUME/etc/openfoam" "$@"
